AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/RedundantReturn:
  Enabled: false

Layout/LineLength:
  Max: 125

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
