export default {
  env: {
    browser: true,
    node: true,
  },
  extends: ['eslint:recommended'],
  rules: {
    'no-console': 'warn',
    'no-debugger': 'warn',
    'no-eval': 'error',
    'no-alert': 'warn',
    'no-unused-vars': 'warn',
    'no-undef': 'error',
    'no-irregular-whitespace': 'error',
    'no-unsafe-finally': 'error',
    'no-magic-numbers': 'warn',
    'no-trailing-spaces': 'warn',
    'no-mixed-spaces-and-tabs': 'error',
    'no-duplicate-imports': 'warn',
    'no-empty-function': 'warn',
    'no-empty': 'warn',
    'no-template-curly-in-string': 'error',
    'no-unsafe-optional-chaining': 'warn',
  },
};
