//
//  DPoPProof.swift
//  TangemModules
//
//  Created by [REDACTED_AUTHOR]
//  Copyright © 2026 Tangem AG. All rights reserved.
//

/// Demonstrating Proof-of-Possession ([RFC 9449 OAuth 2.0 DPoP](https://www.rfc-editor.org/rfc/rfc9449.html)):
/// a short-lived JWS that proves possession of the device's private key, generated fresh per request and never persisted.
///
/// Generated by ``DPoPProofGenerator`` and attached to a request via the headers:
///   | header          | value                                                                                 |
///   | ---             | ---                                                                                   |
///   | `DPoP`          | This proof's ``value``, verbatim                                                      |
///   | `Authorization` | `DPoP <access token>` — ``SessionTokens/accessToken``'s ``SessionTokens/Token/jwt``   |
///
/// Sent on every session-authenticated request:
///   | request             | endpoint                          |
///   | ---                 | ---                               |
///   | token refresh       | `POST /mobile/token/refresh`      |
///   | wallet registration | `POST /mobile/wallet/register`    |
///
/// - SeeAlso: ``DeviceSignature/rawRepresentation`` for the signature this proof is built from.
public struct DPoPProof: Equatable, Sendable {
    /// The compact JWS serialization, three base64url segments joined by dot character: `<header>.<payload>.<signature>`.
    ///
    /// - `header`: `{typ: "dpop+jwt", alg: "ES256", jwk: {kty: "EC", crv: "P-256", x, y}}`,
    ///   with `x`/`y` split from ``DevicePublicKey/rawPoint``.
    ///
    /// - `payload`:
    ///     - `jti` (unique per proof),
    ///     - `htm` (the request's method)
    ///     - `htu` (the request's URI, without query or fragment)
    ///     - `iat` (issued-at)
    ///     - `ath` (present only when this proof accompanies an access-token-bearing request).
    ///
    /// - `signature`: ``DeviceSignature/rawRepresentation`` over `<header>.<payload>`.
    public let value: String
}
