platform :ios, '11.0'
use_frameworks!


target 'BlockchainSdk' do
    project 'BlockchainSdk.xcodeproj'
    
    pod 'BigInt', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'Moya'
    pod 'RxSwift'
    pod 'Moya/RxSwift'
    pod 'Sodium'
    pod 'SwiftCBOR'
    pod 'stellar-ios-mac-sdk', '~> 1.7.2'
    pod 'BinanceChain', :git => 'https://bitbucket.org/tangem/swiftbinancechain.git', :tag => '0.0.4'
    #pod 'BinanceChain', :path => '/Users/alexander.osokin/repos/tangem/SwiftBinanceChain'
    pod 'HDWalletKit', :git => 'https://bitbucket.org/tangem/hdwallet.git', :tag => '0.3.8'
    #pod 'HDWalletKit', :path => '/Users/alexander.osokin/repos/tangem/HDWallet'
    #pod 'web3swift', :path => '/Users/alexander.osokin/repos/tangem/web3swift'
    pod 'web3swift', :git => 'https://bitbucket.org/tangem/web3swift.git', :tag => '2.2.2'
    pod 'AnyCodable-FlightSchool'
end
