platform :ios, '11.0'
use_frameworks!


target 'BlockchainSdk' do
    project 'BlockchainSdk.xcodeproj'
    
    pod 'stellar-ios-mac-sdk'
    pod 'BigInt', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'web3.swift.pod'
    pod 'Moya'
    pod 'RxSwift'
    pod 'Moya/RxSwift'
    pod 'BinanceChain', :git => 'https://github.com/Tangem/binanceChain.git', :tag => '0.1'
end
