name: Fetch translations (Lokalise)

on:
  #schedule:
  #  - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:
    inputs:
      langs:
        description: 'Languages'  # TODO: Add Example
        default: 'en,fr,de,ja,ru,es,uk_UA,zh-Hant'  # TODO: Pass empty string by default
        type: string

jobs:
  update-localizations:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4  # v6.1.0
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_SERVICE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run localization fastlane lane
        env:
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_APP_PROJECT_ID }}
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_ACCESS_TOKEN }}
        run: |
          bundle exec fastlane update_translations languages:${{ github.event.inputs.langs }}

      # TODO: Update texts and add id
      - name: Push changes and open a pull-request
        env:
          GH_TOKEN: ${{ github.token }}
          SOURCE_BRANCH: lokalise-translations  # TODO: Add id
          TARGET_BRANCH: ${{ github.ref_name }}
        run: |
          git config --global user.name 'Tangem Service'
          git config --global user.email 'gitservice@tangem.com'
          git checkout -b $SOURCE_BRANCH $TARGET_BRANCH
          git add 'Tangem/Resources/Localizations'
          git commit -S -m "Fetch all translations"
          git push --set-upstream origin $SOURCE_BRANCH --force
          gh pr create --base $TARGET_BRANCH --head $SOURCE_BRANCH --title "Update translations" --body "" --draft # TODO: TEMP